### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by romanlab** [logzio/logzio-bunyan#1]
getting this when trying to run the tutorial as is.
`TypeError: logzioBunyanStream is not a constructor`

Running node 8.2.1

**Comment by romanlab** [comment]
The problem is completely different - the package downloaded from npm is not this one, it's: https://github.com/jksdua/bunyan-logzio

**Comment by AlonMiz** [comment]
Thanks, 
We've changed the repository name and the Readme file and now you can install it with this name: logzio-bunyan.
