### ISSUE TITLE
please update logzio-nodejs dependency

### ISSUE THREAD

**Issue by adrai** [logzio/logzio-bunyan#4]
https://github.com/logzio/logzio-nodejs/issues/45

**Comment by idohalevi** [comment]
@adrai 
Thanks for the reminder:)
I'll try to do it the latest at the beginning of next week

**Comment by adrai** [comment]
any update?

**Comment by idohalevi** [comment]
@adrai 
Sorry for taking the time. #5

**Comment by adrai** [comment]
Thanks.
waiting for the npm publish ;-)
